runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: my-second-project-191112:europe-west1:outofskindb
env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  INSTANCE_CONNECTION_NAME: my-second-project-191112:europe-west1:outofskindb