runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: my-second-project-191112:europe-west1:outofskindb
env_variables:
  SQL_USER: root
  SQL_PASSWORD: root
  SQL_DATABASE: oldsite
  INSTANCE_CONNECTION_NAME: my-second-project-191112:europe-west1:outofskindb